// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgcetuluevvuvxeelsww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnY2V0dWx1ZXZ2dXZ4ZWVsc3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1Mzk3OTUsImV4cCI6MjA3MjExNTc5NX0.hr7LZqM5KwDVCNb5amKPmHQ_9-CLosFQvI0FgUXlsR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});